# Copy this file into your private app repo at:
#   .github/workflows/notify-public-releases.yml
#
# It fires whenever you publish a release in that repo and
# tells Solution-App-releases to pull the APK across.
#
# Required secret in the PRIVATE repo:
#   RELEASES_REPO_TOKEN  – a fine-grained PAT that has:
#     • Contents (read & write) on Singulary-tee/Solution-App-releases
#     • Actions (read & write) on Singulary-tee/Solution-App-releases

name: Notify public releases repo

on:
  release:
    types: [published]

jobs:
  trigger-sync:
    runs-on: ubuntu-latest
    steps:
      - name: Dispatch sync-apk-release workflow
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.RELEASES_REPO_TOKEN }}
          script: |
            await github.rest.repos.createDispatchEvent({
              owner: 'Singulary-tee',
              repo:  'Solution-App-releases',
              event_type: 'apk-release',
              client_payload: {
                // The private repo that published the release, e.g. "Singulary-tee/aafiya"
                source_repo:  process.env.GITHUB_REPOSITORY,
                // The tag that was just published, e.g. "v1"
                release_tag:  context.payload.release.tag_name,
                // A short identifier used when naming the public release, e.g. "aafiya"
                app_name:     context.payload.repository.name,
              },
            });
